In [2]:
import numpy as np
ai = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10], [-2 ,-5 ,6]])

In [30]:

dim = ai.shape[1]  # Dimension of the matrix X
X = np.eye(dim)  # Initial guess for X
X = np.random.uniform(-1, 1 , dim **2).reshape(dim, dim)
X = np.linalg.svd(X)[0]
X = X @ np.diag([1, 2, 3]) @ X.T

In [63]:
def constraint_objective(X,points):
    outer_products = np.array([np.outer(point,point) for point in points])
    # return np.sum(outer_products,axis=0)
    dim = ai.shape[1]
    val = np.array([a.T@X@a -1 for a in points])
    gradients = outer_products * np.broadcast_to(val[:,np.newaxis,np.newaxis],(points.shape[0],dim,dim))
    return np.sum(gradients,axis=0)
constraint_objective(X,ai)

(array([[[ 2.50490820e+01,  5.00981639e+01,  7.51472459e+01],
         [ 5.00981639e+01,  1.00196328e+02,  1.50294492e+02],
         [ 7.51472459e+01,  1.50294492e+02,  2.25441738e+02]],
 
        [[ 2.38127002e+03,  2.97658752e+03,  3.57190503e+03],
         [ 2.97658752e+03,  3.72073440e+03,  4.46488129e+03],
         [ 3.57190503e+03,  4.46488129e+03,  5.35785754e+03]],
 
        [[ 2.07388419e+04,  2.37015336e+04,  2.96269170e+04],
         [ 2.37015336e+04,  2.70874670e+04,  3.38593337e+04],
         [ 2.96269170e+04,  3.38593337e+04,  4.23241671e+04]],
 
        [[ 4.00002431e+02,  1.00000608e+03, -1.20000729e+03],
         [ 1.00000608e+03,  2.50001520e+03, -3.00001824e+03],
         [-1.20000729e+03, -3.00001824e+03,  3.60002188e+03]]]),
 array([ 25.04908197, 148.82937618, 423.24167136, 100.00060787]))

(array([1., 2., 3.]),
 array([[ 0.04701747, -0.06974226, -0.99645641],
        [ 0.99570616,  0.08290659,  0.04117941],
        [-0.07974086,  0.99411393, -0.07334086]]))